### PR TITLE
Allow overriding page for customizations

### PR DESCRIPTION
**Pull request by mabdullahsari**
Hey 👋

This small PR allows one to register a custom page which extends from the base class to change certain elements about the page itself e.g. the icon, sort priority, slug etc.

Thank you for the package!

### CODE REVIEW

**Comment by ryangjchandler** [comment]
Could you also add this to the README please?

**Comment by mabdullahsari** [comment]
> Could you also add this to the README please?

Definitely. Is it fine like this?

**Comment by mabdullahsari** [comment]
@ryangjchandler Would you say it's ready to be merged like this? 🙌 Thanks for taking your time.

**Review by ryangjchandler — APPROVED** [review]

**Comment by ryangjchandler** [comment]
Released in v0.2.1.

**Pull request merged**
